In [1]:
from env import *
from fonctions import *
import numpy as np
import gurobipy as gp
from gurobipy import GRB
import time

In [2]:
nblig=10
nbcol=15
N=15
P=[1,0.6]

In [11]:
t = np.zeros(len(P))
v = np.zeros(len(P))
tp = np.zeros(len(P))
vp = np.zeros(len(P))
for j in range(len(P)):
    p = P[j]
    env = Env(nblig,nbcol,p,0.2,[0.1,0.2,0.3,0.4]) 
    for i in range(N):
        cases=env.reset()
        ts = time.time()
        p,val=dual_pl_mono(env,0.9)
        te = time.time()
        t[j]+=te-ts
        v[j]+=val
        ts2 = time.time()
        pp,valp =dual_pl_mono(env,0.99,True)
        te2 = time.time()
        tp[j]+=te2-ts2
        vp[j]+=valp
t=t/N
v=v/N
tp=tp/N
vp=vp/N

In [12]:
t

array([0.16603204, 0.14292528])

In [13]:
v

array([53104.50894342, 52476.64989091])

In [14]:
tp

array([0.20940493, 0.34352508])

In [15]:
vp

array([128396.77054409, 127336.07777431])

In [17]:
gamma = [0.9,0.7,0.5]
p = 0.6

t = np.zeros(len(gamma))
v = np.zeros(len(gamma))
for j in range(len(gamma)):
    g = gamma[j]
    env = Env(nblig,nbcol,p,0.2,[0.1,0.2,0.3,0.4]) 
    for i in range(N):
        cases=env.reset()
        ts = time.time()
        policy,val=dual_pl_mono(env,g)
        te = time.time()
        t[j]+=te-ts
        v[j]+=val
t=t/N
v=v/N

In [18]:
t

array([0.15252948, 0.15144623, 0.12779689])

In [19]:
v

array([53112.20456081, 12944.35646844,  5321.6847292 ])