In [1]:
from env import *
from fonctions import *
import numpy as np
import gurobipy as gp
from gurobipy import GRB

In [2]:
env=Env(10,10,1,0.1,[0.1,0.2,0.3,0.4])

In [13]:
cases=env.reset()

In [14]:
cases[:,:,0]

array([[1, 1, 2, 3, 3, 3, 4, 1, 2, 3],
       [3, 2, 2, 4, 1, 2, 4, 3, 3, 3],
       [4, 3, 3, 4, 4, 3, 0, 3, 2, 3],
       [4, 4, 1, 3, 2, 2, 3, 4, 4, 3],
       [1, 1, 2, 4, 4, 1, 2, 1, 4, 3],
       [4, 2, 4, 3, 2, 3, 3, 3, 4, 1],
       [4, 2, 4, 3, 2, 3, 2, 4, 4, 3],
       [3, 4, 4, 3, 3, 3, 4, 2, 2, 4],
       [2, 2, 1, 3, 4, 3, 1, 2, 4, 2],
       [4, 4, 4, 3, 2, 3, 1, 2, 3, 2]])

In [15]:
cases[:,:,1]

array([[8, 9, 3, 8, 6, 1, 6, 1, 2, 3],
       [7, 8, 8, 3, 1, 1, 2, 9, 8, 9],
       [5, 5, 8, 6, 3, 6, 0, 6, 9, 5],
       [2, 2, 2, 9, 9, 8, 1, 8, 8, 5],
       [5, 6, 4, 8, 4, 1, 7, 9, 9, 9],
       [2, 8, 1, 1, 3, 4, 1, 6, 6, 6],
       [8, 6, 6, 5, 8, 7, 4, 3, 2, 5],
       [4, 9, 4, 1, 1, 3, 5, 6, 6, 7],
       [6, 4, 1, 7, 6, 4, 2, 1, 7, 8],
       [2, 3, 5, 6, 1, 6, 5, 7, 5, 6]])

In [6]:
nb,v,policy=value_iteration(env,0.99,max_iteration=2000)

In [7]:
policy

array([[1., 1., 0., 1., 1., 3., 1., 1., 1., 2.],
       [3., 3., 1., 1., 1., 3., 3., 1., 1., 1.],
       [3., 3., 3., 1., 1., 1., 0., 1., 1., 2.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 3., 1., 1., 1., 3., 3., 1., 1., 1.],
       [1., 0., 1., 1., 1., 0., 0., 1., 1., 1.],
       [3., 3., 1., 1., 1., 1., 0., 3., 1., 1.],
       [3., 1., 3., 3., 3., 1., 1., 3., 1., 1.],
       [3., 3., 3., 3., 3., 3., 1., 1., 3., 1.],
       [0., 0., 0., 0., 0., 0., 3., 3., 3., 0.]])

In [8]:
simuler(env,policy,problem="risque")

(-43, array([ 3., 12., 12., 16.]))

In [16]:
policy,val,pm=minmax_policy(env,0.99)

Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (linux64)
Thread count: 1 physical cores, 1 logical processors, using up to 1 threads
Optimize a model with 1670 rows, 401 columns and 2702 nonzeros
Model fingerprint: 0xbdb98ba5
Coefficient statistics:
  Matrix range     [1e-02, 9e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 1568 rows and 15 columns
Presolve time: 0.02s
Presolved: 102 rows, 386 columns, 1122 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   1.668538e+03   0.000000e+00      0s
     310    8.2340053e+02   0.000000e+00   0.000000e+00      0s

Solved in 310 iterations and 0.04 seconds
Optimal objective  8.234005332e+02


In [17]:
pn=normalise(policy)

In [18]:
simuler(env,pn,problem="equilibre")

mixte


(54, array([ -4., -12., -23., -15.]))