In [1]:
from generateur import *
import numpy as np

In [2]:
g = generator(10,10,0.1,[0.1,0.2,0.3,0.4],0.6)

In [3]:
cases=g.random_init()

couleurs
[[1 2 3 0 3 3 2 3 4 2]
 [3 2 2 2 2 4 1 3 1 4]
 [4 1 0 2 3 3 1 4 1 4]
 [4 4 4 2 2 4 4 4 3 3]
 [2 0 3 3 2 3 0 4 4 2]
 [3 1 3 4 4 3 4 3 3 2]
 [4 3 4 4 2 2 3 4 0 0]
 [0 0 1 3 4 4 3 3 4 0]
 [3 3 3 3 3 3 1 2 3 4]
 [2 0 3 4 3 3 3 4 2 2]]
chiffre
[[1 9 3 0 7 5 4 1 4 7]
 [6 3 9 1 2 1 4 3 2 7]
 [4 9 0 6 9 6 8 2 3 1]
 [7 5 9 8 3 4 7 6 5 6]
 [4 0 4 7 5 5 0 5 6 2]
 [9 7 7 6 8 3 6 7 6 9]
 [7 5 6 9 3 5 2 9 0 0]
 [0 0 4 7 6 5 2 3 2 0]
 [4 6 1 6 9 2 5 9 4 7]
 [3 0 5 7 3 7 7 7 6 7]]


In [4]:
type(cases[0,0,0])

numpy.int64