In [2]:
from env import *
from fonctions import *
import numpy as np
import gurobipy as gp
from gurobipy import GRB
import time

In [3]:
nblig=10
nbcol=15
N=15
P=[1,0.6]

In [4]:
t = np.zeros(len(P))
v = np.zeros(len(P))
tp = np.zeros(len(P))
vp = np.zeros(len(P))
for j in range(len(P)):
    p = P[j]
    env = Env(nblig,nbcol,p,0.2,[0.1,0.2,0.3,0.4]) 
    for i in range(N):
        cases=env.reset()
        ts = time.time()
        p,val=dual_pl_mono(env,0.99)
        te = time.time()
        t[j]+=te-ts
        v[j]+=val
        ts2 = time.time()
        pp,valp =dual_pl_mono(env,0.99,True)
        te2 = time.time()
        tp[j]+=te2-ts2
        vp[j]+=valp
t=t/N
v=v/N
tp=tp/N
vp=vp/N


--------------------------------------------
--------------------------------------------

Academic license - for non-commercial use only - expires 2021-01-25
Using license file /home/yuhan/gurobi.lic


In [5]:
t

array([0.18572388, 0.16949682])

In [6]:
v

array([128081.17795173, 128893.51295474])

In [7]:
tp

array([0.27224127, 0.32667751])

In [8]:
vp

array([128046.02020204, 128854.93351808])

In [8]:
gamma = [0.9,0.7,0.5]
p = 0.6

t = np.zeros(len(gamma))
v = np.zeros(len(gamma))
for j in range(len(gamma)):
    g = gamma[j]
    env = Env(nblig,nbcol,p,0.2,[0.1,0.2,0.3,0.4]) 
    for i in range(N):
        cases=env.reset()
        ts = time.time()
        policy,val=dual_pl_mono(env,g)
        te = time.time()
        t[j]+=te-ts
        v[j]+=val
t=t/N
v=v/N

In [9]:
t

array([0.18942502, 0.13864202, 0.13781123])

In [10]:
v

array([50402.73163748, 12641.0027356 ,  5359.6489162 ])